# Base image
FROM python:3.8-slim-buster

# Set work directory
WORKDIR /app

# Install dependencies
# COPY requirements.txt .

# Copy app code
COPY . .

RUN pip install -r requirements.txt
# Expose port
EXPOSE 5000 

# Run app
CMD [ "python", "json_api.py" ]